Gemfile
Made changes in Gemfile to change the rails version as 5.1.6
=> rails version to 5.1.6

.codeclimate.yml, Jenkinsfile, code_climate_coverage_branch.sh, docker/web/Dockerfile
This will enable code coverage reporting
=> Enable code coverage reporting

config/webpacker.yml, docker/web/Dockerfile
Trying to fix pack references 404 in preint
=> update symlink to web packs

Jenkinsfile, app/javascript/_services/api/api.js, app/javascript/_services/api/api.test.js, config/initializers/webpacker.rb
More changes to align with the cloud deployments
=> Update countyadmin url paths to cap

docker-compose.yml
Updating the docker-compose file to get list of users from actual implementation instead of calling the Mock Services from Perry
=> Update Docker compose to get list of users.

app/javascript/home/home.js, app/javascript/home/home.test.js, app/javascript/views/userDetail/UserDetail.jsx, app/javascript/views/userDetail/UserDetail.test.jsx, app/javascript/views/usersList/UsersList.test.js
Adds rails relative url to links on list and detail pages
=> Adjust react links with rails relative root url

Jenkinsfile
Update semantic version number generated for Docker hub to 73
=> Update semantic version number to match sprint

app/javascript/_services/users/user.service.js, app/javascript/_services/users/user.service.test.js, app/javascript/views/userDetail/UserDetail.jsx
when the records are first loaded, the state has arrays.  if the multi select isn't modified the array remained (wasn't turned into a string). and so wasn't able to String split it.  I added la test to prove it and logic to fix it.
=> Handle case of initial load value in the state which is already an array

Jenkinsfile, docker/web/Dockerfile
fixed Jenkinsfile references to path for cap-stable. build
=> Cog 189 fix docker compiling assets

app/assets/stylesheets/application.scss, app/javascript/containers/detailsContainer.js, app/javascript/views/addUser/AddUser.jsx, app/javascript/views/addUser/AddUser.test.js, app/javascript/views/addUser/AddVerifiedUser.jsx, app/javascript/views/addUser/AddVerifiedUser.test.js, app/javascript/views/addUser/VerifyUser.jsx, app/javascript/views/addUser/VerifyUser.test.js
- Disable Verify Button when Email or RacfId is empty
- Add Alert to display the verification_message instead of card
- Fix small space bugs
=> COG-216-Bug-fix

Jenkinsfile, app/javascript/views/usersList/UsersList.jsx, app/javascript/views/usersList/UsersList.test.js
Reverts ca-cwds/county-admin#66
=> Revert "Cap v1.1.0" to restore the Add User button for CAP 1.2 work

app/javascript/selectors/userListSelector.js, app/javascript/selectors/userListSelector.test.js, app/javascript/views/addUser/AddUserDetail.jsx, app/javascript/views/addUser/VerifyUser.jsx, app/javascript/views/userDetail/UserDetail.jsx
=> COG-136-Quick-fix

docker-compose.yml, package.json, scripts/seed-users, yarn.lock
Publishes the es port and adds a node script (invocable with `yarn
seed-users`) to generate 300 Madera county users.
This is to support pagination dev for [COG-12](https://osi-cwds.atlassian.net/browse/COG-12?focusedCommentId=96654&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-96654)
=> Add script to generate fake users in es

app/javascript/views/addUser/AddUserDetail.jsx, app/javascript/views/addUser/AddUserDetail.test.js, app/javascript/views/usersList/UsersList.jsx, app/javascript/views/usersList/UsersList.test.js
This recreates the work overridden by the original COG-112 branch
=> Replace end date with Office name and add testing of field headers

app/javascript/views/usersList/UsersList.jsx, app/javascript/views/usersList/UsersList.test.js
Now fix the Status column to display Active / Inactive.
=> Cog 112 reproduction

app/javascript/views/usersList/UsersList.scss
=> Pixel pushing pagination components for IE

app/javascript/views/userDetail/UserDetailEdit.jsx, app/javascript/views/userDetail/UserDetailEdit.test.js
https://osi-cwds.atlassian.net/browse/COG-301
=> COG-301 Clicking on Edit, CMS Login Disappears

app/controllers/cap_base_controller.rb, app/javascript/App.jsx, app/javascript/App.test.js, app/javascript/views/header/HeaderComponent.jsx, app/javascript/views/header/HeaderComponent.test.jsx, config/routes.rb, lib/infrastructure/cwds_authenticator.rb, lib/infrastructure/security_gateway.rb, spec/controllers/cap_base_controller_spec.rb, spec/lib/infrastructure/security_gateway_spec.rb
Which User story does this relate to (link)?
- https://osi-cwds.atlassian.net/browse/COG-67
Brief feature description
- Logout from county-admin.
=> COG-67 Add logout functionality in county admin

spec/acceptance/add_user_spec.rb, spec/acceptance/user_edit_details_spec.rb, spec/acceptance/user_list_page_spec.rb, spec/acceptance_helper.rb
Adds pending tests on each page to test accessibility with spec matchers.  Output will show up in the accessibility test run.
=> Add pending accessible ui tests

package.json
- run `yarn dev` locally with `.env` file pointing to integration.
=> Yarn script to run app locally in dev mode

spec/acceptance/support/login_helper.rb, spec/acceptance/user_edit_details_spec.rb, spec/acceptance/user_forgot_password_spec.rb, spec/acceptance/user_login_spec.rb
- https://osi-cwds.atlassian.net/browse/COG-510
-
=> Fix failing cognito acceptance tests

Jenkinsfile, JenkinsfileCodeReview
https://osi-cwds.atlassian.net/browse/FIT-296
Added SemVer to cap using the Jenkins shared a library, Each PR should be added with a label (Major, Minor or patch) else the PR Jenkins will fail at "Check for SemVer label", based on the label the semantic numbering with change.
=> Added the SemVer on cap

Jenkinsfile, JenkinsfileCodeReview
- https://osi-cwds.atlassian.net/browse/FIT-296
-
=> Fit 296 implement sem ver for cap

Jenkinsfile
- https://osi-cwds.atlassian.net/browse/FIT-296
- Final PR tested against my branch on Jenkins master build semantic version worked as expected. Please review 
http://jenkins.dev.cwds.io:8080/view/cap/job/cap-stable/513/console
=> added back the newTag

app/assets/stylesheets/application.scss, app/javascript/views/usersList/UsersList.scss
[-COG-1066](https://osi-cwds.atlassian.net/browse/COG-1066)
-Style fix for ChangeLog Component
=> fix changeLog style

app/javascript/common/DropDown.js, app/javascript/common/DropDown.test.js, app/javascript/views/userDetail/UserDetailEdit.jsx, app/javascript/views/userDetail/UserDetailEdit.test.js, app/javascript/views/usersList/UsersList.jsx, app/javascript/views/usersList/UsersList.test.js
-NA
- { Select } from '@cwds/components' updated onChange methods for DropDown component according to the react-select v2.1.1 (https://react-select.com/upgrade-guide)
=> Update dropdown component

Jenkinsfile, JenkinsfileCodeReview
- No Jira Story
- Added the trigger properties to fix the Jenkins master build and not to override the token and post parameters.
=> Fix for the Jenkins master build

app/javascript/selectors/detailSelector.js, app/javascript/selectors/detailSelector.test.js, app/javascript/views/userDetail/Notes.jsx, app/javascript/views/userDetail/Notes.test.js
- https://osi-cwds.atlassian.net/browse/COG-1221
- Displays same count of emoji's in all 5 browsers, Each emojis is counted as 2 characters.
=> COG-1221 Fix emoji's character count on Notes Field.

app/javascript/views/usersList/Pagination.jsx, app/javascript/views/usersList/UsersList.scss
[https://osi-cwds.atlassian.net/browse/COG-1150](https://osi-cwds.atlassian.net/browse/COG-1150)
- Pagination is not aligned in fire-fox, IE , and edge browsers
=> Fix the pagination styles in IE, Edge, fire-fox browsers

JenkinsDeploy
- COG-1260 -- params for RACFID in acceptance tests
-
=> Fix jenkins params

JenkinsDeploy
- https://osi-cwds.atlassian.net/browse/COG-1194
- Syntax error on jenkinsfile array
=> COG-1194 Fix jenkins pipeline

app/javascript/containers/detailsContainer.js, app/javascript/views/userDetail/UserDetail.jsx, app/javascript/views/userDetail/UserDetail.test.js
- https://osi-cwds.atlassian.net/browse/COG-1308
- Missing Profile name and Office names are back when user is opened in new tab instead of clicking on the user list directly.
=> COG-1308 Fix Missing Profile Name and Office Name in User Detail View 

app/javascript/reducers/searchUserListReducers.js, app/javascript/views/searchUserList/SearchUserList.jsx, app/javascript/views/searchUserList/SearchUserList.test.js
- n/a
- fixes search with first_name, email, racfid.
=> Add a check for value

app/assets/stylesheets/application.scss, app/javascript/views/searchUserList/SearchResultComponent.jsx, app/javascript/views/searchUserList/SearchResultComponent.test.js
- https://osi-cwds.atlassian.net/browse/COG-1369
- Fixes the alignment of the Dashboard link in userlist and user detail page.
=> COG-1369 fix dashboard link to revert it back to original position

app/assets/stylesheets/application.scss, app/javascript/views/searchUserList/SearchResultComponent.jsx, app/javascript/views/searchUserList/SearchResultComponent.test.js, app/javascript/views/searchUserList/SearchUserList.test.js
-  https://osi-cwds.atlassian.net/browse/COG-1369
- Fixes the user detail link from the user list page.
=> COG-1369 Fixes the User detail Link

app/javascript/views/searchUserList/SearchUserList.jsx, spec/acceptance/search_user_list_office_spec.rb, spec/acceptance/search_user_list_page_spec.rb, spec/acceptance/support/search_user_list_page_helpers.rb, spec/acceptance/support/user_detail_page_helpers.rb, spec/acceptance/user_edit_details_spec.rb
- COG-1369 and related stories
- Updates all acceptance tests to work with latest UI changes in the search user list page
=> Cog 1369 acceptance tests

JenkinsfileAcceptance
[Automation: Fix test run error when running acceptance test in staging pipeline](https://osi-cwds.atlassian.net/browse/FIT-529)
Automation: Fix test run error when running acceptance test in staging pipeline (https://jenkins.prodctrl.cwds.io/job/staging/job/acceptance-test-cap/)
fixed another compilation issue
No tests, jenkins pipeline fix only
=> Fit 529 fix test run error in staging pipeline

app/javascript/views/searchUserList/SearchUserList.jsx, app/javascript/views/searchUserList/SearchUserList.test.js
- https://osi-cwds.atlassian.net/browse/COG-1423
- Disables the checkbox and office selection dropdown fields when editing the search criteria
=> COG-1423 Disable checkbox and office filter dropdown when editing

lib/elastic/user_query_builder.rb, spec/controllers/api/search_user_list_controller_spec.rb, spec/lib/elastic/user_query_builder_spec.rb
- COG-1340
- Tuning to boost all matching types for first and last name.
=> Boost all name searches equally

spec/acceptance/county/user_forgot_password_spec.rb, spec/acceptance/support/user_detail_page_helpers.rb
- stabilize MFA requirement for test
- stabilize permission selection for acceptance testing
=> Acceptance test stability

app/javascript/reducers/searchUserListReducers.js, app/javascript/reducers/searchUserListReducers.test.js, app/javascript/selectors/searchUserListSelector.js, app/javascript/selectors/searchUserListSelector.test.js, app/javascript/views/searchUserList/SearchUserList.jsx, app/javascript/views/searchUserList/SearchUserList.test.js
- https://osi-cwds.atlassian.net/browse/COG-1436
- Fixes the preselection of office value for office admin.
=> COG-1436 fix preselect office value for office admin

app/javascript/views/groupUsersList/GroupUsersList.jsx, app/javascript/views/searchUserList/SearchResultComponent.jsx, app/javascript/views/searchUserList/SearchResultComponent.test.js, app/javascript/views/userDetail/UserDetail.jsx, app/javascript/views/userDetail/UserDetail.test.js
- https://osi-cwds.atlassian.net/browse/COG-1448
- Text change of bread crumb.
- Fix for case: Issue when visiting user detail, directly by entering the URL
=> COG-1448-Text change for bread crumb and fix for routing

JenkinsDeploy
-https://osi-cwds.atlassian.net/browse/FIT-580
- removed acceptance tests from the rollback block.
=> Fix: FIT-580. removed acceptance tests from the rollback block.

app/assets/stylesheets/application.scss, app/controllers/api/user_detail_controller.rb, app/javascript/_services/users/user.service.test.js, app/javascript/containers/detailsContainer.js, app/javascript/selectors/detailSelector.js, app/javascript/selectors/detailSelector.test.js, app/javascript/views/userDetail/UserDetail.jsx, app/javascript/views/userDetail/UserDetailEdit.jsx, app/javascript/views/userDetail/UserDetailEdit.test.js, lib/users/user_details.rb, spec/controllers/api/user_detail_controller_spec.rb, spec/lib/users/user_details_spec.rb
- https://osi-cwds.atlassian.net/browse/COG-1474
- Edit cell phone number or add cell phone number for users. Not a mandatory field for users to enter information before save.
=> COG-1474 Edit cell phone number on User Profile 

JenkinsDeploy, app/assets/stylesheets/application.scss, app/javascript/actions/searchUserListActions.js, app/javascript/actions/searchUserListActions.test.js, app/javascript/common/UserMessage.js, app/javascript/common/UserMessage.test.js, app/javascript/containers/searchUserListContainer.js, app/javascript/reducers/searchUserListReducers.js, app/javascript/reducers/searchUserListReducers.test.js, app/javascript/sagas/changeUserStatusSaga.js, app/javascript/sagas/changeUserStatusSaga.test.js, app/javascript/views/searchUserList/SearchResultComponent.jsx, app/javascript/views/searchUserList/SearchResultComponent.test.js, app/javascript/views/searchUserList/SearchResults.jsx, app/javascript/views/searchUserList/SearchResults.test.jsx, app/javascript/views/searchUserList/SearchUserList.jsx, app/javascript/views/searchUserList/SearchUserList.scss, app/javascript/views/searchUserList/SearchUserList.test.js
- COG-1469
- Allows viewing and unlocking of locked users, with a clearable acknowledgement when unlocking is complete.
=> Cog 1469 Unlock users from Search page
